spring.application.name=indexsearch-server
spring.main.banner-mode=off
logging.file.name=log/indexsearch-server.log
logging.level.root=INFO

application.data.dir=data
application.metadata.dir=metadata
application.index.dir=index